### ISSUE TITLE
Choosing the name

### ISSUE THREAD

**Issue by ribeiroct** [bioinformatics-ua/scaleus#2]
As asked, i was trying to think of a few names:

I looked into the source for the COEUS name, and is the greek titan of knowledge. Should you follow this line of reasoning ?

 So how about calling it Gnosis, which means experience knowledge in greek ?

Other option would be Hermes which is the fastest of the gods (for the scalability and speed of the solution), and Zeus messenger.

If we look for the roman equivalents, we could call it Mercury which is the equivalent of Hermes, or Polus, which is the roman equivalent of Coeus.

So here are my ideas:
- Gnosis
- Hermes
- Mercury
- Polus

I would tend towards Hermes probably.

**Comment by ribeiroct** [comment]
@sernadela

**Comment by ribeiroct** [comment]
If you want to run into another direction, and choose a portuguese name, i would call it the "Sistema Escalável de Triplo Armazenamento (SETA)"

**Comment by bastiao** [comment]
@ribeiroct Hermes is already used by OHDSI :) By the way, they are using all names of greek mythology

https://github.com/OHDSI

Anyway, I like SETA, 
In English: Scalable Triple Store (STS)
Or - TripleSS ("Triple double S")

**Comment by sernadela** [comment]
Thanks for the feedback! In my opinion, SCALEUS its a better bet due to the association of COEUS framework.
